import { configureStore } from '@reduxjs/toolkit';
import scoreReducer, { Score } from './store/scoreSlice';

const initialScores: Score[] = [
  { username: 'McRamble', score: '00:30:23', amount: '₹50000', timestamp: Date.now() },
  { username: 'Anjum', score: '00:40:23', amount: '₹5000', timestamp: Date.now() },
  { username: 'Pragati', score: '00:50:23', amount: '₹500', timestamp: Date.now() },
  { username: 'Muhammed', score: '01:00:23', amount: '', timestamp: Date.now() },
  { username: 'Razzi', score: '01:10:23', amount: '', timestamp: Date.now() },
  { username: 'Hannibal', score: '01:20:23', amount: '', timestamp: Date.now() },
  { username: 'Vijay', score: '01:30:23', amount: '', timestamp: Date.now() },
  { username: 'Rajveer', score: '01:40:23', amount: '', timestamp: Date.now() },
  { username: 'Prashant', score: '01:50:23', amount: '', timestamp: Date.now() },
  { username: 'Chandra', score: '02:00:23', amount: '', timestamp: Date.now() },
  { username: 'Samantha', score: '02:10:23', amount: '', timestamp: Date.now() },
  { username: 'Nathaniel', score: '02:20:23', amount: '', timestamp: Date.now() },
  { username: 'Amit', score: '02:30:23', amount: '', timestamp: Date.now() },
  { username: 'Neha', score: '02:40:23', amount: '', timestamp: Date.now() },
  { username: 'Oliver', score: '02:50:23', amount: '', timestamp: Date.now() },
  { username: 'Sophia', score: '03:00:23', amount: '', timestamp: Date.now() },
  { username: 'Liam', score: '03:10:23', amount: '', timestamp: Date.now() },
  { username: 'Emma', score: '03:20:23', amount: '', timestamp: Date.now() },
  { username: 'Noah', score: '03:30:23', amount: '', timestamp: Date.now() },
  { username: 'Isabella', score: '03:40:23', amount: '', timestamp: Date.now() },
  { username: 'James', score: '03:50:23', amount: '', timestamp: Date.now() },
  { username: 'Mia', score: '04:00:23', amount: '', timestamp: Date.now() },
  { username: 'Benjamin', score: '04:10:23', amount: '', timestamp: Date.now() },
  { username: 'Charlotte', score: '04:20:23', amount: '', timestamp: Date.now() },
  { username: 'Lucas', score: '04:30:23', amount: '', timestamp: Date.now() },
  { username: 'Amelia', score: '04:40:23', amount: '', timestamp: Date.now() },
  { username: 'Henry', score: '04:50:23', amount: '', timestamp: Date.now() },
  { username: 'Harper', score: '05:00:23', amount: '', timestamp: Date.now() },
  { username: 'Alexander', score: '05:10:23', amount: '', timestamp: Date.now() },
  { username: 'Evelyn', score: '05:20:23', amount: '', timestamp: Date.now() },
  { username: 'Sebastian', score: '05:30:23', amount: '', timestamp: Date.now() },
  { username: 'Abigail', score: '05:40:23', amount: '', timestamp: Date.now() },
  { username: 'Jackson', score: '05:50:23', amount: '', timestamp: Date.now() },
  { username: 'Ella', score: '06:00:23', amount: '', timestamp: Date.now() },
  { username: 'Aiden', score: '06:10:23', amount: '', timestamp: Date.now() },
  { username: 'Avery', score: '06:20:23', amount: '', timestamp: Date.now() },
  { username: 'Matthew', score: '06:30:23', amount: '', timestamp: Date.now() },
  { username: 'Scarlett', score: '06:40:23', amount: '', timestamp: Date.now() },
  { username: 'Samuel', score: '06:50:23', amount: '', timestamp: Date.now() },
  { username: 'Grace', score: '07:00:23', amount: '', timestamp: Date.now() },
  { username: 'David', score: '07:10:23', amount: '', timestamp: Date.now() },
  { username: 'Chloe', score: '07:20:23', amount: '', timestamp: Date.now() },
  { username: 'Joseph', score: '07:30:23', amount: '', timestamp: Date.now() },
  { username: 'Victoria', score: '07:40:23', amount: '', timestamp: Date.now() },
  { username: 'Carter', score: '07:50:23', amount: '', timestamp: Date.now() },
  { username: 'Riley', score: '08:00:23', amount: '', timestamp: Date.now() },
  { username: 'Owen', score: '08:10:23', amount: '', timestamp: Date.now() },
  { username: 'Zoey', score: '08:20:23', amount: '', timestamp: Date.now() },
  { username: 'Wyatt', score: '08:30:23', amount: '', timestamp: Date.now() },
  { username: 'Nora', score: '08:40:23', amount: '', timestamp: Date.now() },
  { username: 'John', score: '08:50:23', amount: '', timestamp: Date.now() },
  { username: 'Lily', score: '09:00:23', amount: '', timestamp: Date.now() },
  { username: 'Luke', score: '09:10:23', amount: '', timestamp: Date.now() },
  { username: 'Eleanor', score: '09:20:23', amount: '', timestamp: Date.now() },
  { username: 'Levi', score: '09:30:23', amount: '', timestamp: Date.now() },
  { username: 'Hannah', score: '09:40:23', amount: '', timestamp: Date.now() },
  { username: 'Isaac', score: '09:50:23', amount: '', timestamp: Date.now() },
  { username: 'Lillian', score: '10:00:23', amount: '', timestamp: Date.now() },
  { username: 'Gabriel', score: '10:10:23', amount: '', timestamp: Date.now() },
  { username: 'Addison', score: '10:20:23', amount: '', timestamp: Date.now() },
  { username: 'Julian', score: '10:30:23', amount: '', timestamp: Date.now() },
  { username: 'Aubrey', score: '10:40:23', amount: '', timestamp: Date.now() },
  { username: 'Anthony', score: '10:50:23', amount: '', timestamp: Date.now() },
  { username: 'Ellie', score: '11:00:23', amount: '', timestamp: Date.now() },
  { username: 'Dylan', score: '11:10:23', amount: '', timestamp: Date.now() },
  { username: 'Stella', score: '11:20:23', amount: '', timestamp: Date.now() },
  { username: 'Isaiah', score: '11:30:23', amount: '', timestamp: Date.now() },
  { username: 'Natalie', score: '11:40:23', amount: '', timestamp: Date.now() },
  { username: 'Jack', score: '11:50:23', amount: '', timestamp: Date.now() },
  { username: 'Zoe', score: '12:00:23', amount: '', timestamp: Date.now() },
  { username: 'Grayson', score: '12:10:23', amount: '', timestamp: Date.now() },
  { username: 'Leah', score: '12:20:23', amount: '', timestamp: Date.now() },
  { username: 'Jonathan', score: '12:30:23', amount: '', timestamp: Date.now() },
  { username: 'Hazel', score: '12:40:23', amount: '', timestamp: Date.now() },
  { username: 'Adrian', score: '12:50:23', amount: '', timestamp: Date.now() },
  { username: 'Violet', score: '13:00:23', amount: '', timestamp: Date.now() },
  { username: 'Ezra', score: '13:10:23', amount: '', timestamp: Date.now() },
  { username: 'Aurora', score: '13:20:23', amount: '', timestamp: Date.now() },
  { username: 'Charles', score: '13:30:23', amount: '', timestamp: Date.now() },
  { username: 'Savannah', score: '13:40:23', amount: '', timestamp: Date.now() },
  { username: 'Thomas', score: '13:50:23', amount: '', timestamp: Date.now() },
  { username: 'Aria', score: '14:00:23', amount: '', timestamp: Date.now() },
  { username: 'Caleb', score: '14:10:23', amount: '', timestamp: Date.now() },
  { username: 'Penelope', score: '14:20:23', amount: '', timestamp: Date.now() },
  { username: 'Christopher', score: '14:30:23', amount: '', timestamp: Date.now() },
  { username: 'Mila', score: '14:40:23', amount: '', timestamp: Date.now() },
  { username: 'Jaxon', score: '14:50:23', amount: '', timestamp: Date.now() },
  { username: 'Paisley', score: '15:00:23', amount: '', timestamp: Date.now() },
  { username: 'Maverick', score: '15:10:23', amount: '', timestamp: Date.now() },
  { username: 'Claire', score: '15:20:23', amount: '', timestamp: Date.now() },
  { username: 'Josiah', score: '15:30:23', amount: '', timestamp: Date.now() },
  { username: 'Skylar', score: '15:40:23', amount: '', timestamp: Date.now() },
  { username: 'Isaiah', score: '15:50:23', amount: '', timestamp: Date.now() },
  { username: 'Bella', score: '16:00:23', amount: '', timestamp: Date.now() },
  { username: 'Adam', score: '16:10:23', amount: '', timestamp: Date.now() },
  { username: 'Camila', score: '16:20:23', amount: '', timestamp: Date.now() },
  { username: 'Nathan', score: '16:30:23', amount: '', timestamp: Date.now() },
  { username: 'Lucy', score: '16:40:23', amount: '', timestamp: Date.now() },
  { username: 'Xavier', score: '16:50:23', amount: '', timestamp: Date.now() },
  { username: 'Madeline', score: '17:00:23', amount: '', timestamp: Date.now() },
  { username: 'Leo', score: '17:10:23', amount: '', timestamp: Date.now() },
  { username: 'Rylee', score: '17:20:23', amount: '', timestamp: Date.now() },
  { username: 'Lincoln', score: '17:30:23', amount: '', timestamp: Date.now() },
  { username: 'Arianna', score: '17:40:23', amount: '', timestamp: Date.now() },
  { username: 'Eli', score: '17:50:23', amount: '', timestamp: Date.now() },
  { username: 'Sarah', score: '18:00:23', amount: '', timestamp: Date.now() },
  { username: 'Landon', score: '18:10:23', amount: '', timestamp: Date.now() },
  { username: 'Kennedy', score: '18:20:23', amount: '', timestamp: Date.now() },
  { username: 'Zachary', score: '18:30:23', amount: '', timestamp: Date.now() },
  { username: 'Kinsley', score: '18:40:23', amount: '', timestamp: Date.now() },
  { username: 'Asher', score: '18:50:23', amount: '', timestamp: Date.now() },
  { username: 'Eva', score: '19:00:23', amount: '', timestamp: Date.now() },
  { username: 'Connor', score: '19:10:23', amount: '', timestamp: Date.now() },
  { username: 'Cora', score: '19:20:23', amount: '', timestamp: Date.now() },
  { username: 'Jeremiah', score: '19:30:23', amount: '', timestamp: Date.now() },
  { username: 'Elena', score: '19:40:23', amount: '', timestamp: Date.now() },
  { username: 'Cameron', score: '19:50:23', amount: '', timestamp: Date.now() },
  { username: 'Willow', score: '20:00:23', amount: '', timestamp: Date.now() },
  { username: 'Robert', score: '20:10:23', amount: '', timestamp: Date.now() },
  { username: 'Sarah', score: '20:20:23', amount: '', timestamp: Date.now() },
  { username: 'William', score: '20:30:23', amount: '', timestamp: Date.now() },
  { username: 'Rachel', score: '20:40:23', amount: '', timestamp: Date.now() },
  { username: 'Joseph', score: '20:50:23', amount: '', timestamp: Date.now() },
  { username: 'Rebecca', score: '21:00:23', amount: '', timestamp: Date.now() },
  { username: 'Daniel', score: '21:10:23', amount: '', timestamp: Date.now() },
  { username: 'Hannah', score: '21:20:23', amount: '', timestamp: Date.now() },
  { username: 'Ethan', score: '21:30:23', amount: '', timestamp: Date.now() },
  { username: 'Abigail', score: '21:40:23', amount: '', timestamp: Date.now() },
  { username: 'Alexander', score: '21:50:23', amount: '', timestamp: Date.now() },
  { username: 'Mia', score: '22:00:23', amount: '', timestamp: Date.now() },
  { username: 'Nicholas', score: '22:10:23', amount: '', timestamp: Date.now() },
  { username: 'Elizabeth', score: '22:20:23', amount: '', timestamp: Date.now() },
  { username: 'Joshua', score: '22:30:23', amount: '', timestamp: Date.now() },
  { username: 'Lily', score: '22:40:23', amount: '', timestamp: Date.now() },
  { username: 'Andi', score: '22:50:23', amount: '', timestamp: Date.now() },
];

const preloadedState = {
  scores: {
    scores: initialScores,
  },
};

const store = configureStore({
  reducer: {
    scores: scoreReducer,
  },
  preloadedState,
});

export type RootState = ReturnType<typeof store.getState>; //dispatching an action
export type AppDispatch = typeof store.dispatch;

export default store;
